### ISSUE TITLE
Don't bring up bare rules heading

### ISSUE THREAD

**Issue by Fryyyyy** [Fryyyyy/Fryatog#11]
```
02:54 < Staunch> !702.53
02:54 <+Fryatog> 702.53: Bloodthirst
02:54 < Staunch> ugh
```

**Comment by Petzku** [comment]
Pulling at least the first subrule is a good idea. Here it works well:
`702.53a Bloodthirst is a static ability. "Bloodthirst N" means "If an opponent was dealt damage this turn, this permanent enters the battlefield with N +1/+1 counters on it."`

In other cases, less so:
`702.7a First strike is a static ability that modifies the rules for the combat damage step. (See rule 510, "Combat Damage Step.")`
`702.15a Lifelink is a static ability.`

So maybe the next subrule (702.Xb) should be pulled as well in these cases. The question is how to detect these cases.
One idea is to see if the first subrule contains the word "means". It filters away all ones which do explain the keyword, but has a few false negatives (e.g. Fuse). It's not perfect, but more heuristics could maybe solve the problem.

702.Xa [without "means"](https://pastebin.com/Np9yZJzp) and [with "means"](https://pastebin.com/ucVU6sLe).

**Comment by Fryyyyy** [comment]
:) Thanks for the analysis @Petzku !

**Comment by Fryyyyy** [comment]
Plz everyone take a look at this change, see if i've forgotten or missed anything
