### ISSUE TITLE
[Low Priority] Link to long rules?

### ISSUE THREAD

**Issue by Fryyyyy** [Fryyyyy/Fryatog#112]
Instead of listing eighteen gazillion creature subtypes, should we just give a link to Yawgatog?

**Comment by Villawhatever** [comment]
Only concern with this is that Yawg sometimes takes a non-trivial amount of time to update his site; I've seen it be a week or two.

Not a _major_ isuse, mind, but something to consider.

**Comment by Fryyyyy** [comment]
https://github.com/Fryyyyy/Fryatog/commit/dd667368c9326c459aeaec5580ed3e448c607bb3
