### ISSUE TITLE
Stepmom doesn't work?

### ISSUE THREAD

**Issue by Villawhatever** [Fryyyyy/Fryatog#142]
Live Fryatog doesn't recognize `stepmom` as valid shorthand, but it works fine on my dev client. ?

**Comment by Fryyyyy** [comment]
Fixed in live but should check that we normalise before checking short_names

**Comment by Fryyyyy** [comment]
ncn := normaliseCardName(input)
	
	// See if it's a known short name of a card.
	if qualifiedName, ok := shortCardNames[input]; ok {



We do but then we don't use it!
SMRT

Reminder to myself to change this to shortCardNames[ncn]
