### ISSUE TITLE
Scryfall fuzzy sometimes matches non-English cards

### ISSUE THREAD

**Issue by Fryyyyy** [Fryyyyy/Fryatog#146]
!Flash and put !Nyxbloom Ancient

Steppenbrand {3}{R} · Hexerei · Zerstöre alle Ebenen. · 9ED-U,8ED-U,6ED-U,POR-U,5ED-U,[...] · Vin,Leg,Mod
Nyxbloom Ancient {4}{G}{G}{G} · Enchantment Creature — Elemental · 5/5 · Trample \ If you tap a permanent for mana, it produces three times as much of that mana instead. · THB-M ·

Because "Flash and" matches Flash Fires and Steppendbr _and_

Possible answer:
If card returned isn't in English (and it wasn't a foreign language request), check if the first word of the query is the exact name of a magic card and return that

**Comment by Fryyyyy** [comment]
Still caching foreign version ??

```
08:49:13 < Villawhatever> !failure is so close to being a good card
08:49:15 < Fryatog> Villawhatever: Fracaso miserable {2}{U}{U} · Instantáneo · Contrarresta el hechizo objetivo. Su controlador descarta una carta. · PLC-U 
                    · Vin,Leg,Mod
08:49:19 < Villawhatever> ...bruh
08:49:23 < Villawhatever> !failure
08:49:23 < Fryatog> Villawhatever: Failure {1}{U} · Instant · Return target spell to its owner's hand. · PAKH-R,AKH-R · Vin,Leg,Mod,Pio
08:49:24 < Fryatog> Villawhatever: Comply {W} · Sorcery · Aftermath (Cast this spell only from your graveyard. Then exile it.) \ Choose a card name. Until 
                    your next turn, your opponents can't cast spells with the chosen name. · PAKH-R,AKH-R · Vin,Leg,Mod,Pio
08:49:31 < Taki> LOL
08:49:35 < Villawhatever> this foreign language shit is a fracaso miserable for sure
08:49:52 < Taki> is that Spanish Dismal Failure?
08:50:16 < Villawhatever> lmaoooo so the card cache is stuck now
08:50:17 < Villawhatever> !dismal failure
08:50:18 < Fryatog> Villawhatever: Fracaso miserable {2}{U}{U} · Instantáneo · Contrarresta el hechizo objetivo. Su controlador descarta una carta. · PLC-U 
                    · Vin,Leg,Mod
08:50:22 < Villawhatever> womp womp
```

**Comment by Villawhatever** [comment]
So it continues:

`<teddyyy> !erebos titan
<Fryatog> teddyyy: Erebos' Titan {1}{B}{B}{B} · Kreatur — Riese · 5/5 · Solange deine Gegner keine Kreaturen kontrollieren, hat Erebos' Titan Unzerstörbarkeit. (Schaden und Effekte, die „zerstören", zerstören ihn nicht.)Immer wenn eine Kreaturenkarte den Friedhof eines Gegners verlässt, kannst du eine Karte abwerfen. Falls du dies tust, bringe Erebos' Titan aus deinem Friedhof auf [...]
<Fryatog> deine Hand zurück. · ORI-M · Vin,Leg,Mod,Pio`
