### ISSUE TITLE
Return Errors presented by a Scryfall search?

### ISSUE THREAD

**Issue by Villawhatever** [Fryyyyy/Fryatog#164]
`<mekkis> !search text=suspend cmc=7`

`<Fryatog> mekkis: Too many cards returned (583 > 5)`

Of course, this is so huge because `text=suspend` isn't a valid search term, so scryfall ignores it. Is it worth returning this error somewhere (either DMing the user or as a second line in the channel I guess) to let them know that the bad result is because of user error?

**Comment by Fryyyyy** [comment]
How do we get the error message?

**Comment by Villawhatever** [comment]
There's a `warning` object returned at the same level as the `data` object.
`https://api.scryfall.com/cards/search?q=is%3Aslick+cmc%3E12`
has 
`"warnings": [
    "Invalid expression “is:slick” was ignored. Checking if cards are “slick” is not supported"
  ],`

**Comment by Fryyyyy** [comment]
Yup, ok, we'll need to add the "warnings" attribute to the CardSearchResult struct

**Comment by Villawhatever** [comment]
DM or in channel? I'll start working on it next weekend

**Comment by Fryyyyy** [comment]
I think it's fine as part of the error message we display back to the user.
We could _just_ show the warnings if there are any, since "too many cards" is its own form of error but generated by us...

i.e
```
if(scryfallWarnings) { respond with them }
elif (too long) { tell them } 
else { results }
```
