### ISSUE TITLE
Specific rule examples

### ISSUE THREAD

**Issue by Villawhatever** [Fryyyyy/Fryatog#166]
I could've sworn we already had this implemented.

Basically, I'd like to be able to `!ex [rule] [which]` and get that specific example. Turns out some of these nerds have 3+ examples and ain't nobody need all that.

**Comment by Fryyyyy** [comment]
We do examples but not an optional "which" parameter.
I think we figured that would be sufficient...

**Comment by Villawhatever** [comment]
Yeah; a single example is enough _most_ of the time just because, well, the vast majority of rules only have one example.

Came up today with 614.12, which is already quite a long rule, and only the third example was relevant.

Ionno. Not hugely pressed either way about it. Can close if you feel like it.
