### ISSUE TITLE
Define ability words?

### ISSUE THREAD

**Issue by Fryyyyy** [Fryyyyy/Fryatog#20]
Should we have a custom list of definitions?

**Comment by Petzku** [comment]
Would be helpful. Needing to be maintained manually is undesirable, but probably unavoidable if we want the feature. Ability words change very rarely (if ever) though, so it would only really mean writing a definition whenever new ones get added.

**Comment by Fryyyyy** [comment]
Who wants to volunteer to write these

**Comment by Villawhatever** [comment]
I'm down. Tell me what how you want them formatted.

**Comment by Fryyyyy** [comment]
I guess a JSON file

```
{
"name": "Thingy",
"description": "Does the thing"
}
```
