### ISSUE TITLE
Paginate excessively long responses

### ISSUE THREAD

**Issue by Villawhatever** [Fryyyyy/Fryatog#24]
Something very large like `!205.3m` (the list of creature types) spits the _whole_ thing into the channel, which is... a lot. Maybe trim to two full outputs and then offer `!next` to get the next page?

**Comment by Fryyyyy** [comment]
I hate that !next feature from Datatog, tbh, plus it means we have to remember a lot more state

**Comment by Fryyyyy** [comment]
If it's rules, maybe we can just give a link to https://yawgatog.com/resources/magic-rules/#R2053m
