### ISSUE TITLE
Rulings order

### ISSUE THREAD

**Issue by Fryyyyy** [Fryyyyy/Fryatog#38]
Check that our order is the same as Gatherer, so the index numbers align

**Comment by fenhl** [comment]
You're using Scryfall's API, right? I think they do something weird like reversed order of rulings that have the same date.

**Comment by Fryyyyy** [comment]
Blerrrrrrrrrrgh

**Comment by Villawhatever** [comment]
What card(s) have we verified this is broken on? Scryfall rulings are indexed and the ones I've checked line up with Gatherer, and they're still properly ordered in `fetchRulings()`

**Comment by Fryyyyy** [comment]
`07:42 <@luma> !ruling ixidron 2
07:42 <+Fryatog> luma: 2006-09-25: If Ixidron and another creature are entering the battlefield at the same time, the other creature enters the battlefield face up.
07:42 <@luma> silly bot, that isn't ruling 2`
