### ISSUE TITLE
!cards are a little generous?

### ISSUE THREAD

**Issue by Villawhatever** [Fryyyyy/Fryatog#42]
`<Phasing12> Hello! I was wondering if Selvala, Explorer Returned flip triggers work. If I use Selvala and two nonlands are revealed, is that two triggers of life & mana gain or are they summe into
<Fryatog> Phasing12: Mana Tithe {W} · Instant · Counter target spell unless its controller pays {1}. · PLC-C · Vin,Leg,Mod`

**Comment by Fryyyyy** [comment]
After discussion this is probably a WONTFIX
